version: '3'

services:
  app:
    build: .
    command: npm run dev -- --host 0.0.0.0 --port 3000
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - nm:/app/node_modules

volumes:
  nm:
